//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfo
    {
        public long AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string IFSCCode { get; set; }
        public string CustomerName { get; set; }
        public decimal Balance { get; set; }
    }
}
